update all dockerfiles through m4 file

diff --git a/SG1/centos-7/media/dev/Dockerfile b/SG1/centos-7/media/dev/Dockerfile
--- a/SG1/centos-7/media/dev/Dockerfile
+++ b/SG1/centos-7/media/dev/Dockerfile
@@ -4,7 +4,7 @@
 # To update, modify the template and regenerate.
 FROM centos:7 AS build
 
-RUN yum install -y -q epel-release
+RUN yum install -y -q epel-release centos-release-scl && rm -rf /var/yum/cache/*
 
 
 
@@ -13,16 +13,19 @@ RUN mkdir -p /opt/build && mkdir -p /opt/dist
 ENV PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig
 
 RUN yum install -y wget gcc-c++ make libcurl-devel zlib-devel
-ARG CMAKE_VER_1=3.13.1
+
+# build cmake
 ARG CMAKE_REPO=https://cmake.org/files
-RUN wget -O - ${CMAKE_REPO}/v${CMAKE_VER_1%.*}/cmake-${CMAKE_VER_1}.tar.gz | tar xz && \
-    cd cmake-${CMAKE_VER_1} && \
+RUN cd /opt/build && \
+    wget -O - ${CMAKE_REPO}/v3.19/cmake-3.19.4.tar.gz | tar xz && \
+    cd cmake-3.19.4 && \
     ./bootstrap --prefix=/usr/local --system-curl && \
     make -j$(nproc) && \
     make install
 
-RUN yum install -y wget make autoconf diffutils automake gcc-c++ epel-release
+RUN yum install -y wget make autoconf diffutils automake gcc-c++
 
+# build libogg
 ARG LIBOGG_REPO=https://downloads.xiph.org/releases/ogg/libogg-1.3.4.tar.gz
 
 RUN cd /opt/build && \
@@ -35,8 +38,8 @@ RUN cd /opt/build && \
 
 RUN yum install -y wget make autoconf diffutils automake
 
+# build libvorbis
 ARG LIBVORBIS_REPO=https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.gz
-
 RUN cd /opt/build && \
     wget -O - ${LIBVORBIS_REPO} | tar xz && \
     cd libvorbis-1.3.7 && \
@@ -47,6 +50,7 @@ RUN cd /opt/build && \
 
 RUN yum install -y wget gcc-c++ autoconf libtool make automake
 
+# build libfdkaac
 ARG LIBFDKAAC_REPO=https://github.com/mstorsjo/fdk-aac/archive/v0.1.6.tar.gz
 RUN cd /opt/build && \
     wget -O - ${LIBFDKAAC_REPO} | tar xz && \
@@ -59,6 +63,7 @@ RUN cd /opt/build && \
 
 RUN yum install -y wget autoconf libtool make
 
+# build libopus
 ARG LIBOPUS_REPO=https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
 RUN cd /opt/build && \
     wget -O - ${LIBOPUS_REPO} | tar xz && \
@@ -70,6 +75,7 @@ RUN cd /opt/build && \
 
 RUN yum install -y wget tar gcc-c++ make bzip2
 
+# build nasm
 ARG NASM_REPO=https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.bz2
 RUN cd /opt/build && \
     wget -O - ${NASM_REPO} | tar xj && \
@@ -79,8 +85,9 @@ RUN cd /opt/build && \
      make -j$(nproc) && \
      make install
 
-RUN yum install -y git cmake make autoconf diffutils
+RUN yum install -y git make autoconf diffutils
 
+# build libvpx
 ARG LIBVPX_REPO=https://chromium.googlesource.com/webm/libvpx.git
 RUN cd /opt/build && \
     git clone ${LIBVPX_REPO} -b v1.8.2 --depth 1 && \
@@ -90,30 +97,35 @@ RUN cd /opt/build && \
     make install DESTDIR=/opt/dist && \
     make install
 
-RUN yum install -y git cmake3 make
+RUN yum install -y git make
 
+# build libaom
 ARG LIBAOM_REPO=https://aomedia.googlesource.com/aom
 RUN cd /opt/build && \
     git clone ${LIBAOM_REPO} -b v2.0.0 --depth 1 && \
     cd aom/build && \
-    cmake3 -DBUILD_SHARED_LIBS=ON -DENABLE_NASM=ON -DENABLE_TESTS=OFF -DENABLE_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=lib64 .. && \
+    cmake -DBUILD_SHARED_LIBS=ON -DENABLE_NASM=ON -DENABLE_TESTS=OFF -DENABLE_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=lib64 .. && \
     make -j$(nproc) && \
     make install DESTDIR=/opt/dist && \
     make install
 
-RUN yum install -y git cmake make autoconf diffutils
+RUN yum install -y git make autoconf diffutils
 
+# build libx264
 ARG LIBX264_REPO=https://github.com/mirror/x264
 RUN cd /opt/build && \
     git clone ${LIBX264_REPO} -b stable --depth 1 && \
     cd x264 && \
-    ./configure --prefix=/usr/local --libdir=/usr/local/lib64 --enable-shared && \
+    ./configure --prefix=/usr/local --libdir=/usr/local/lib64 \
+        --enable-shared && \
     make -j$(nproc) && \
     make install DESTDIR=/opt/dist && \
     make install
 
 RUN yum install -y wget tar gcc-c++ make
-ARG YASM_REPO=https://github.com/OpenVisualCloud/Dockerfiles-Resources/raw/master/yasm-1.3.0.tar.gz
+
+# build yasm
+ARG YASM_REPO=https://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
 RUN cd /opt/build && \
     wget -O - ${YASM_REPO} | tar xz
 RUN cd /opt/build/yasm-1.3.0 && \
@@ -123,8 +135,9 @@ RUN cd /opt/build/yasm-1.3.0 && \
     make -j $(nproc) && \
     make install
 
-RUN yum install -y cmake make numactl-devel libpciaccess-devel
+RUN yum install -y make numactl-devel libpciaccess-devel
 
+# build libx265
 ARG LIBX265_REPO=https://github.com/videolan/x265/archive/3.3.tar.gz
 RUN cd /opt/build && \
     wget -O - ${LIBX265_REPO} | tar xz && \
@@ -135,6 +148,8 @@ RUN cd /opt/build && \
     make install
 
 RUN yum install -y meson wget tar gcc-c++
+
+# build dav1d
 ARG DAV1D_REPO=https://code.videolan.org/videolan/dav1d/-/archive/0.7.1/dav1d-0.7.1.tar.gz
 RUN cd /opt/build && \
   wget -O - ${DAV1D_REPO} | tar xz
@@ -144,135 +159,157 @@ RUN cd /opt/build/dav1d-0.7.1 && \
   ninja install && \
   DESTDIR=/opt/dist ninja install
 
-RUN yum install -y wget tar gcc-c++ make git cmake3
+RUN yum install -y wget tar gcc-c++ make git 
+
+# build svt-hevc
 ARG SVT_HEVC_REPO=https://github.com/OpenVisualCloud/SVT-HEVC
 RUN cd /opt/build && \
-    git clone ${SVT_HEVC_REPO}
+    git clone -b v1.5.0 --depth 1 ${SVT_HEVC_REPO}
 RUN cd /opt/build/SVT-HEVC/Build/linux && \
-    git checkout v1.5.0 && \
-    cmake3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
+    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
     make -j $(nproc) && \
     make install DESTDIR=/opt/dist && \
     make install
 
-RUN yum install -y wget tar gcc-c++ make git cmake3
-ARG SVT_AV1_REPO=https://github.com/AOMediaCodec/SVT-AV1
+RUN yum install -y wget tar gcc-c++ make git 
+
+# build svt av1
+ARG SVT_AV1_REPO=https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v0.8.6/SVT-AV1-v0.8.6.tar.gz
 RUN cd /opt/build && \
-    git clone ${SVT_AV1_REPO} -b v0.8.5 --depth 1 && \
+    wget -O - ${SVT_AV1_REPO} | tar zx && \
+    mv SVT-AV1-v0.8.6 SVT-AV1 && \
     cd SVT-AV1/Build/linux && \
-    cmake3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
+    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
     make -j $(nproc) && \
-    sed -i 's/SvtAv1dec/SvtAv1Dec/' SvtAv1Dec.pc && \
+    sed -i "s/SvtAv1dec/SvtAv1Dec/" SvtAv1Dec.pc && \
     make install DESTDIR=/opt/dist && \
     make install
 
-RUN yum install -y wget tar gcc-c++ make git cmake3 centos-release-scl
+RUN yum install -y wget tar gcc-c++ make git devtoolset-9
+
+# build svt vp9
 ARG SVT_VP9_REPO=https://github.com/OpenVisualCloud/SVT-VP9
 RUN cd /opt/build && \
     git clone ${SVT_VP9_REPO} -b v0.2.1 --depth 1 && \
     cd SVT-VP9/Build/linux && \
-  ( yum install -y devtoolset-9-gcc-c++ && \
-    source /opt/rh/devtoolset-9/enable && \
-    cmake3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
-    make -j $(nproc) && \
+    (. /opt/rh/devtoolset-9/enable && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
+    make -j $(nproc) ) && \
     make install DESTDIR=/opt/dist && \
-    make install )
+    make install
 
-RUN yum install -y cmake gcc-c++ make wget
-ARG GMMLIB_REPO=https://github.com/VCDP/gmmlib/archive/intel-media-sg1-pv1.1.tar.gz
+RUN yum install -y gcc-c++ make wget
+
+# build gmmlib
+ARG GMMLIB_REPO=https://github.com/VCDP/gmmlib/archive/intel-media-sg1-pv1.2.tar.gz
 RUN cd /opt/build && \
   wget -O - ${GMMLIB_REPO} | tar xz
-RUN cd /opt/build/gmmlib-intel-media-sg1-pv1.1 && mkdir build && cd build && \
+RUN cd /opt/build/gmmlib-intel-media-sg1-pv1.2 && mkdir build && cd build && \
   cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 .. && \
   make -j$(nproc) && \
   make install DESTDIR=/opt/dist && \
   make install
 
 RUN yum install -y automake gcc libdrm-devel libtool make pkg-config wget which libX11-devel libXfixes-devel libXext-devel wayland-devel
-ARG LIBVA2_REPO=https://github.com/VCDP/libva/archive/intel-media-sg1-pv1.1.tar.gz
+
+# build libva2
+ARG LIBVA2_REPO=https://github.com/VCDP/libva/archive/intel-media-sg1-pv1.2.tar.gz
 RUN cd /opt/build && \
   wget -O - ${LIBVA2_REPO} | tar xz
-RUN cd /opt/build/libva-intel-media-sg1-pv1.1 && \
+RUN cd /opt/build/libva-intel-media-sg1-pv1.2 && \
   ./autogen.sh --prefix=/usr/local --libdir=/usr/local/lib64 && \
   make -j$(nproc) && \
   make install DESTDIR=/opt/dist && \
   make install
 
-RUN yum install -y cmake gcc-c++ libpciaccess-devel make pkg-config wget centos-release-scl
-ARG MEDIA_DRIVER_REPO=https://github.com/VCDP/media-driver/archive/intel-media-sg1-pv1.1.tar.gz
+RUN yum install -y gcc-c++ libpciaccess-devel make pkg-config wget devtoolset-9
+
+# build media driver
+ARG MEDIA_DRIVER_REPO=https://github.com/VCDP/media-driver/archive/intel-media-sg1-pv1.2.tar.gz
 RUN cd /opt/build && \
   wget -O - ${MEDIA_DRIVER_REPO} | tar xz
-RUN cd /opt/build/media-driver-intel-media-sg1-pv1.1 && mkdir build && cd build && \
-  ( yum install -y devtoolset-9-gcc-c++ && \
-    source /opt/rh/devtoolset-9/enable && \
-  cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DENABLE_PRODUCTION_KMD=ON .. && \
-  make -j$(nproc) && \
+RUN cd /opt/build/media-driver-intel-media-sg1-pv1.2 && mkdir build && cd build && \
+  (. /opt/rh/devtoolset-9/enable && cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DENABLE_PRODUCTION_KMD=ON .. && \
+  make -j$(nproc) ) && \
   make install DESTDIR=/opt/dist && \
-  make install )
+  make install
 
-RUN yum install -y cmake gcc gcc-c++ make pkg-config wget centos-release-scl
-ARG MSDK_REPO=https://github.com/VCDP/MediaSDK/archive/intel-media-sg1-pv1.1.tar.gz
+RUN yum install -y gcc gcc-c++ make pkg-config wget devtoolset-9
+
+# build media sdk
+ARG MSDK_REPO=https://github.com/VCDP/MediaSDK/archive/intel-media-sg1-pv1.2.tar.gz
 RUN cd /opt/build && \
-  wget -O - ${MSDK_REPO} | tar xz
-RUN cd /opt/build/MediaSDK-intel-media-sg1-pv1.1 && \
-  mkdir -p build && cd build && \
-  ( yum install -y devtoolset-9-gcc-c++ && \
-    source /opt/rh/devtoolset-9/enable && \
-  cmake \
+    wget -O - ${MSDK_REPO} | tar xz
+RUN cd /opt/build/MediaSDK-intel-media-sg1-pv1.2 && \
+    mkdir -p build && cd build && \
+    (. /opt/rh/devtoolset-9/enable && cmake \
     -DCMAKE_INSTALL_PREFIX=/usr/local \
     -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 \
     -DBUILD_SAMPLES=no \
     -DBUILD_TUTORIALS=OFF \
     .. && \
-  make -j$(nproc) && \
-  make install DESTDIR=/opt/dist && \
-  make install )
+    make -j$(nproc)) && \
+    make install DESTDIR=/opt/dist && \
+    make install
 
-RUN yum install -y wget patch libv4l-devel libass-devel freetype-devel 
+RUN yum install -y wget patch libv4l-devel libass-devel freetype-devel
 
+# build ffmpeg
 ARG FFMPEG_REPO=https://github.com/FFmpeg/FFmpeg/archive/n4.2.2.tar.gz
 RUN cd /opt/build && \
     wget -O - ${FFMPEG_REPO} | tar xz
-
 
 ARG FFMPEG_PATCH_SVT_AV1_REPO=https://github.com/AOMediaCodec/SVT-AV1/archive/v0.8.4.tar.gz
 RUN cd /opt/build && \
     wget -O - ${FFMPEG_PATCH_SVT_AV1_REPO} | tar xz && \
     cd /opt/build/FFmpeg-n4.2.2 && \
     patch -p1 < ../SVT-AV1-0.8.4/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch || true
-
 RUN cd /opt/build/FFmpeg-n4.2.2 && \
     patch -p1 < /opt/build/SVT-HEVC/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch || true
-
 RUN cd /opt/build/FFmpeg-n4.2.2 && \
     patch -p1 < ../SVT-VP9/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch || true
+ARG FFMPEG_PATCH_VAAPI_REPO=https://github.com/OpenVisualCloud/Dockerfiles-Resources/raw/master/ffmpeg-patch-0041-lavc-vaapi_encode_h265-fix-max_transform_hierarchy_d.tar.gz
+RUN cd /opt/build && \
+    wget -O - ${FFMPEG_PATCH_VAAPI_REPO} | tar xz && \
+    cd /opt/build/FFmpeg-n4.2.2 && \
+    patch -p1 < ../0041-lavc-vaapi_encode_h265-fix-max_transform_hierarchy_d.patch || true
+
+ARG FFMPEG_PATCHES_RELEASE_VER=0.2
+ARG FFMPEG_PATCHES_RELEASE_URL=https://github.com/VCDP/CDN/archive/v${FFMPEG_PATCHES_RELEASE_VER}.tar.gz
+ARG FFMPEG_PATCHES_PATH=/opt/build/CDN-${FFMPEG_PATCHES_RELEASE_VER}
+
+RUN cd /opt/build && \
+    wget -O - ${FFMPEG_PATCHES_RELEASE_URL} | tar xz && \
+    cd /opt/build/FFmpeg-n4.2.2 && \
+    find ${FFMPEG_PATCHES_PATH}/FFmpeg_patches -type f -name *.patch -print0 | sort -z | xargs -t -0 -n 1 patch -p1 -i;
 
 RUN cd /opt/build/FFmpeg-n4.2.2 && \
     ./configure --prefix=/usr/local --libdir=/usr/local/lib64 --enable-shared --disable-static --disable-doc --disable-htmlpages \
     --disable-manpages --disable-podpages --disable-txtpages \
-    --enable-gpl     --enable-nonfree     --enable-libass     --enable-libfreetype     --disable-xlib --disable-sdl2         --enable-libmfx     --enable-vaapi     --enable-libv4l2 --enable-indev=v4l2         --enable-libfdk-aac     --enable-libopus     --enable-libvpx     --enable-libvorbis     --enable-libx264     --enable-libx265     --enable-libsvtav1     --enable-libsvthevc     --enable-libsvtvp9     --enable-libaom     --enable-libdav1d     && make -j$(nproc) && \
+    --extra-cflags=-w     --enable-gpl     --enable-nonfree     --enable-libass     --enable-libfreetype     --disable-xlib --disable-sdl2         --enable-libmfx     --enable-vaapi     --enable-libv4l2 --enable-indev=v4l2         --enable-libfdk-aac     --enable-libopus     --enable-libvpx     --enable-libvorbis     --enable-libx264     --enable-libx265     --enable-libsvtav1     --enable-libsvthevc     --enable-libsvtvp9     --enable-libaom     --enable-libdav1d                     && make -j$(nproc) && \
     make install DESTDIR=/opt/dist && \
     make install
 
-RUN echo "Start cleanup" && \
-    rm -rf /opt/dist//usr/local/include && \
-    rm -rf /opt/dist//usr/local/share/doc && \
-    rm -rf /opt/dist//usr/local/share/gtk-doc && \
-    rm -rf /opt/dist//usr/local/share/man && \
-    ( find /opt/dist -name "*.a" -exec rm -f {} \; ) && \
-    echo "Cleanup done"
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib64/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc /opt/dist/usr/local/share/gtk-doc
+RUN rm -rf /opt/dist/usr/local/share/man
 
 FROM centos:7
 LABEL Description="This is the image for FFMPEG and Gstreamer application for media development on centos 7"
 LABEL Vendor="Intel Corporation"
 WORKDIR /home
 
-RUN yum install -y -q epel-release
+RUN yum install -y -q epel-release && rm -rf /var/yum/cache/*
 
 
 # Install
-RUN yum install -y numactl-libs libpciaccess libdrm libX11 libXfixes libXext libwayland-client libass freetype glibc libv4l 
+RUN yum install -y bash numactl-libs libpciaccess libdrm libX11 libXfixes libXext libwayland-client libv4l libass
 
 COPY --from=build /opt/dist /
 RUN echo "/usr/local/lib64" >> /etc/ld.so.conf.d/all-libs.conf && ldconfig
 
+ENV LIBVA_DRIVERS_PATH=/usr/local/lib64/dri
+ENV LIBVA_DRIVER_NAME=iHD
+ENV DISPLAY=:0.0
diff --git a/Xeon/centos-7/media/nginx/Dockerfile b/Xeon/centos-7/media/nginx/Dockerfile
--- a/Xeon/centos-7/media/nginx/Dockerfile
+++ b/Xeon/centos-7/media/nginx/Dockerfile
@@ -2,30 +2,41 @@
 
 # This file is automatically generated from .m4 template.
 # To update, modify the template and regenerate.
-FROM centos:centos7 AS build
+FROM centos:7 AS build
 
-RUN yum install -y -q epel-release
-
+RUN yum install -y -q epel-release && rm -rf /var/yum/cache/*
 
 
 RUN mkdir -p /opt/build && mkdir -p /opt/dist
 
 ENV PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig
 
-RUN yum install -y wget
+RUN yum install -y wget patch
 
+ARG NGINX_FLV_PATCHES_REPO=https://github.com/VCDP/CDN/archive/v0.2.tar.gz
+ARG NGINX_FLV_PATCHES_PATH=/opt/build/CDN-0.2
+RUN cd /opt/build && \
+    wget -O - ${NGINX_FLV_PATCHES_REPO} | tar xz
+
+# build nginx flv
 ARG NGINX_FLV_REPO=https://github.com/winshining/nginx-http-flv-module/archive/v1.2.8.tar.gz
 RUN cd /opt/build && \
-    wget -O - ${NGINX_FLV_REPO} | tar xz
+    wget -O - ${NGINX_FLV_REPO} | tar xz && \
+    cd nginx-http-flv-module-1.2.8 && \
+    mkdir -p BUILD_DEST/var/www/html && \
+    cp -f stat.xsl BUILD_DEST/var/www/html && \
+    find ${NGINX_FLV_PATCHES_PATH}/Nginx-HTTP-FLV_patches -type f -name *.patch -print0 | sort -z | xargs -t -0 -n 1 patch -p1 -i
 
 
 
+# build nginx upload
 ARG NGINX_UPLOAD_REPO=https://github.com/fdintino/nginx-upload-module/archive/2.3.0.tar.gz
 RUN cd /opt/build && \
     wget -O - ${NGINX_UPLOAD_REPO} | tar xz
 
 RUN yum install -y gcc libxslt-devel make pcre-devel wget zlib-devel openssl-devel
 
+# build nginx
 ARG NGINX_REPO=https://nginx.org/download/nginx-1.18.0.tar.gz
 RUN cd /opt/build && \
     wget -O - ${NGINX_REPO} | tar xz && \
@@ -58,6 +69,7 @@ RUN cd /opt/build && \
     && make install DESTDIR=/opt/dist
 
 # NGINX Setup
+COPY nginx.conf /opt/dist/etc/nginx
 RUN mkdir -p /opt/dist/var/www/tmp/client_body && \
     mkdir -p /opt/dist/var/www/tmp/proxy && \
     mkdir -p /opt/dist/var/www/tmp/fastcgi && \
@@ -69,24 +81,22 @@ RUN mkdir -p /opt/dist/var/www/tmp/client_body && \
     mkdir -p /opt/dist/var/www/upload && \
     mkdir -p /opt/dist/var/www/html
 
-RUN echo "Start cleanup" && \
-    rm -rf /opt/dist//usr/local/include && \
-    rm -rf /opt/dist//usr/local/share/doc && \
-    rm -rf /opt/dist//usr/local/share/gtk-doc && \
-    rm -rf /opt/dist//usr/local/share/man && \
-    ( find /opt/dist -name "*.a" -exec rm -f {} \; ) && \
-    echo "Cleanup done"
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib64/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc /opt/dist/usr/local/share/gtk-doc
+RUN rm -rf /opt/dist/usr/local/share/man
 
-FROM openvisualcloud/xeon-centos7-media-ffmpeg:latest
-LABEL Description="This is the base image for NGINX+RTMP centos centos7"
+FROM openvisualcloud/xeon-centos7-media-ffmpeg:-n
+LABEL Description="This is the base image for NGINX+RTMP centos 7"
 LABEL Vendor="Intel Corporation"
 WORKDIR /home
 
-RUN yum install -y -q epel-release
-
-
 # Install
-RUN yum install -y libxml2 libxslt pcre zlib openssl
+RUN yum install -y -q epel-release && rm -rf /var/yum/cache/*
+
+RUN yum install -y libxml2 libxslt pcre zlib openssl11
 
 COPY --from=build /opt/dist /
 RUN echo "/usr/local/lib64" >> /etc/ld.so.conf.d/all-libs.conf && ldconfig
diff --git a/Xeon/centos-7/media/svt/Dockerfile b/Xeon/centos-7/media/svt/Dockerfile
--- a/Xeon/centos-7/media/svt/Dockerfile
+++ b/Xeon/centos-7/media/svt/Dockerfile
@@ -2,9 +2,9 @@
 
 # This file is automatically generated from .m4 template.
 # To update, modify the template and regenerate.
-FROM centos:centos7 AS build
+FROM centos:7 AS build
 
-RUN yum install -y -q epel-release
+RUN yum install -y -q epel-release && rm -rf /var/yum/cache/*
 
 
 
@@ -14,6 +14,7 @@ ENV PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig
 
 RUN yum install -y wget tar gcc-c++ make bzip2
 
+# build nasm
 ARG NASM_REPO=https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.bz2
 RUN cd /opt/build && \
     wget -O - ${NASM_REPO} | tar xj && \
@@ -25,6 +26,7 @@ RUN cd /opt/build && \
 
 RUN yum install -y git cmake3 make
 
+# build libaom
 ARG LIBAOM_REPO=https://aomedia.googlesource.com/aom
 RUN cd /opt/build && \
     git clone ${LIBAOM_REPO} -b v2.0.0 --depth 1 && \
@@ -34,24 +36,23 @@ RUN cd /opt/build && \
     make install DESTDIR=/opt/dist && \
     make install
 
-RUN echo "Start cleanup" && \
-    rm -rf /opt/dist//usr/local/include && \
-    rm -rf /opt/dist//usr/local/share/doc && \
-    rm -rf /opt/dist//usr/local/share/gtk-doc && \
-    rm -rf /opt/dist//usr/local/share/man && \
-    ( find /opt/dist -name "*.a" -exec rm -f {} \; ) && \
-    echo "Cleanup done"
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib64/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc /opt/dist/usr/local/share/gtk-doc
+RUN rm -rf /opt/dist/usr/local/share/man
 
-FROM centos:centos7
-LABEL Description="This is the showcase image for SVT centos centos7"
+FROM openvisualcloud/xeon-centos7-media-ffmpeg:latest
+LABEL Description="This is the showcase image for SVT centos 7"
 LABEL Vendor="Intel Corporation"
 WORKDIR /home
 
-RUN yum install -y -q epel-release
+RUN yum install -y -q epel-release && rm -rf /var/yum/cache/*
 
 
 # Install
-RUN yum install -y 
+RUN yum install -y bash
 
 COPY --from=build /opt/dist /
 RUN echo "/usr/local/lib64" >> /etc/ld.so.conf.d/all-libs.conf && ldconfig
diff --git a/Xeon/ubuntu-18.04/media/svt/Dockerfile b/Xeon/ubuntu-18.04/media/svt/Dockerfile
--- a/Xeon/ubuntu-18.04/media/svt/Dockerfile
+++ b/Xeon/ubuntu-18.04/media/svt/Dockerfile
@@ -14,6 +14,7 @@ RUN apt-get update && \
     ca-certificates wget tar g++ make bzip2 && \
   rm -rf /var/lib/apt/lists/*
 
+# build nasm
 ARG NASM_REPO=https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.bz2
 RUN cd /opt/build && \
     wget -O - ${NASM_REPO} | tar xj && \
@@ -28,6 +29,7 @@ RUN apt-get update && \
     git cmake make && \
   rm -rf /var/lib/apt/lists/*
 
+# build libaom
 ARG LIBAOM_REPO=https://aomedia.googlesource.com/aom
 RUN cd /opt/build && \
     git clone ${LIBAOM_REPO} -b v2.0.0 --depth 1 && \
@@ -37,13 +39,12 @@ RUN cd /opt/build && \
     make install DESTDIR=/opt/dist && \
     make install
 
-RUN echo "Start cleanup" && \
-    rm -rf /opt/dist//usr/local/include && \
-    rm -rf /opt/dist//usr/local/share/doc && \
-    rm -rf /opt/dist//usr/local/share/gtk-doc && \
-    rm -rf /opt/dist//usr/local/share/man && \
-    ( find /opt/dist -name "*.a" -exec rm -f {} \; ) && \
-    echo "Cleanup done"
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc /opt/dist/usr/local/share/gtk-doc
+RUN rm -rf /opt/dist/usr/local/share/man
 
 FROM openvisualcloud/xeon-ubuntu1804-media-ffmpeg:latest
 LABEL Description="This is the showcase image for SVT ubuntu 18.04"
@@ -51,10 +52,7 @@ LABEL Vendor="Intel Corporation"
 WORKDIR /home
 
 # Install
-RUN apt-get update && \
-  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-     && \
-  rm -rf /var/lib/apt/lists/*
+
 
 COPY --from=build /opt/dist /
 RUN echo "/usr/local/lib" >> /etc/ld.so.conf.d/all-libs.conf && ldconfig
diff --git a/XeonE3/ubuntu-20.04/media/nginx/Dockerfile b/XeonE3/ubuntu-20.04/media/nginx/Dockerfile
--- a/XeonE3/ubuntu-20.04/media/nginx/Dockerfile
+++ b/XeonE3/ubuntu-20.04/media/nginx/Dockerfile
@@ -11,15 +11,26 @@ ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
 
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    ca-certificates wget && \
+    ca-certificates wget patch && \
   rm -rf /var/lib/apt/lists/*
 
+ARG NGINX_FLV_PATCHES_REPO=https://github.com/VCDP/CDN/archive/v0.2.tar.gz
+ARG NGINX_FLV_PATCHES_PATH=/opt/build/CDN-0.2
+RUN cd /opt/build && \
+    wget -O - ${NGINX_FLV_PATCHES_REPO} | tar xz
+
+# build nginx flv
 ARG NGINX_FLV_REPO=https://github.com/winshining/nginx-http-flv-module/archive/v1.2.8.tar.gz
 RUN cd /opt/build && \
-    wget -O - ${NGINX_FLV_REPO} | tar xz
+    wget -O - ${NGINX_FLV_REPO} | tar xz && \
+    cd nginx-http-flv-module-1.2.8 && \
+    mkdir -p BUILD_DEST/var/www/html && \
+    cp -f stat.xsl BUILD_DEST/var/www/html && \
+    find ${NGINX_FLV_PATCHES_PATH}/Nginx-HTTP-FLV_patches -type f -name *.patch -print0 | sort -z | xargs -t -0 -n 1 patch -p1 -i
 
 
 
+# build nginx upload
 ARG NGINX_UPLOAD_REPO=https://github.com/fdintino/nginx-upload-module/archive/2.3.0.tar.gz
 RUN cd /opt/build && \
     wget -O - ${NGINX_UPLOAD_REPO} | tar xz
@@ -29,6 +40,7 @@ RUN apt-get update && \
     ca-certificates gcc libpcre3-dev libxslt1-dev make wget zlib1g-dev libssl-dev && \
   rm -rf /var/lib/apt/lists/*
 
+# build nginx
 ARG NGINX_REPO=https://nginx.org/download/nginx-1.18.0.tar.gz
 RUN cd /opt/build && \
     wget -O - ${NGINX_REPO} | tar xz && \
@@ -61,6 +73,7 @@ RUN cd /opt/build && \
     && make install DESTDIR=/opt/dist
 
 # NGINX Setup
+COPY nginx.conf /opt/dist/etc/nginx
 RUN mkdir -p /opt/dist/var/www/tmp/client_body && \
     mkdir -p /opt/dist/var/www/tmp/proxy && \
     mkdir -p /opt/dist/var/www/tmp/fastcgi && \
@@ -72,15 +85,14 @@ RUN mkdir -p /opt/dist/var/www/tmp/client_body && \
     mkdir -p /opt/dist/var/www/upload && \
     mkdir -p /opt/dist/var/www/html
 
-RUN echo "Start cleanup" && \
-    rm -rf /opt/dist//usr/local/include && \
-    rm -rf /opt/dist//usr/local/share/doc && \
-    rm -rf /opt/dist//usr/local/share/gtk-doc && \
-    rm -rf /opt/dist//usr/local/share/man && \
-    ( find /opt/dist -name "*.a" -exec rm -f {} \; ) && \
-    echo "Cleanup done"
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc /opt/dist/usr/local/share/gtk-doc
+RUN rm -rf /opt/dist/usr/local/share/man
 
-FROM openvisualcloud/xeon-ubuntu2004-media-ffmpeg:latest
+FROM openvisualcloud/xeone3-ubuntu2004-media-ffmpeg:-n
 LABEL Description="This is the base image for NGINX+RTMP ubuntu 20.04"
 LABEL Vendor="Intel Corporation"
 WORKDIR /home
@@ -88,7 +100,7 @@ WORKDIR /home
 # Install
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    libpcre3 libxml2 libxslt1.1 zlib1g openssl && \
+    libpcre3 libxml2 libxslt1.1 zlib1g libssl1.1 && \
   rm -rf /var/lib/apt/lists/*
 
 COPY --from=build /opt/dist /
