update all dockerfiles through m4 file (#702)
* update all dockerfiles through m4 file

diff --git a/VCAC-A/ubuntu-18.04/analytics/hddldaemon/Dockerfile b/VCAC-A/ubuntu-18.04/analytics/hddldaemon/Dockerfile
--- a/VCAC-A/ubuntu-18.04/analytics/hddldaemon/Dockerfile
+++ b/VCAC-A/ubuntu-18.04/analytics/hddldaemon/Dockerfile
@@ -1,86 +1,115 @@
 
-FROM ubuntu:18.04 as builder
-WORKDIR /home
+# This file is automatically generated from .m4 template.
+# To update, modify the template and regenerate.
+FROM ubuntu:18.04 AS build
 
-# BUILD TOOLS for HDDLDAEMON image
-RUN apt-get update && apt-get install -y --no-install-recommends cpio sudo python3-pip python3-setuptools wget libboost-filesystem1.65 libboost-thread1.65 libboost-program-options1.65 libjson-c-dev build-essential autoconf automake libtool kmod libelf-dev libusb-1.0-0 lsb-release && \
-    rm -rf /var/lib/apt/lists/*
 
-# Build libusb
-ARG LIBUSB_VER=v1.0.22
-ARG LIBUSB_REPO=https://github.com/libusb/libusb/archive/${LIBUSB_VER}.tar.gz
+RUN mkdir -p /opt/build && mkdir -p /opt/dist
 
-RUN wget -O - ${LIBUSB_REPO} | tar xz && \
+ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
+
+RUN apt-get update && \
+  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+    wget make autoconf automake build-essential ca-certificates libtool libboost-filesystem1.65 libboost-thread1.65 libboost-program-options1.65 libjson-c-dev && \
+  rm -rf /var/lib/apt/lists/*
+
+# build libusb
+ARG LIBUSB_REPO=https://github.com/libusb/libusb/archive/v1.0.22.tar.gz
+RUN cd /opt/build && \
+    wget -O - ${LIBUSB_REPO} | tar xz && \
     cd libusb* && \
     ./autogen.sh enable_udev=no && \
-    make -j "$(nproc)" && \
+    make -j$(nproc) && \
     cp ./libusb/.libs/libusb-1.0.so /lib/x86_64-linux-gnu/libusb-1.0.so.0
 
-# OpenVINO version
-# 2021
-ARG OPENVINO_BUNDLE=l_openvino_toolkit_p_2021.1.110
-ARG OPENVINO_URL=https://registrationcenter-download.intel.com/akdlm/irc_nas/17062/l_openvino_toolkit_p_2021.1.110.tgz
+RUN mkdir -p /opt/dist/lib/x86_64-linux-gnu	&& \
+    cp /lib/x86_64-linux-gnu/libusb-1.0.so.0 /opt/dist/lib/x86_64-linux-gnu/libusb-1.0.so.0
 
+RUN apt-get update && \
+  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+    cpio && \
+  rm -rf /var/lib/apt/lists/*
+
+# Install OpenVINO - Closed source dldt
+ARG OPENVINO_REPO=http://registrationcenter-download.intel.com/akdlm/irc_nas/16803/l_openvino_toolkit_p_2020.4.287.tgz
 
 #Download and unpack OpenVino
-RUN mkdir /tmp2
-RUN wget ${OPENVINO_URL} -P /tmp2
-RUN if [ -f /tmp2/${OPENVINO_BUNDLE}.tgz ]; \
-    then tar xzvf /tmp2/${OPENVINO_BUNDLE}.tgz -C /tmp2 && rm /tmp2/${OPENVINO_BUNDLE}.tgz; \
+RUN mkdir /opt/build/openvino
+RUN wget ${OPENVINO_REPO} -P /opt/build/openvino
+RUN if [ -f /opt/build/openvino/l_openvino_toolkit_p_2020.4.287.tgz ]; \
+    then tar xzvf /opt/build/openvino/l_openvino_toolkit_p_2020.4.287.tgz -C /opt/build/openvino && rm /opt/build/openvino/l_openvino_toolkit_p_2020.4.287.tgz; \
     else echo "Please prepare the OpenVino installation bundle"; \
 fi
 
 # Create a silent configuration file for install
-RUN echo "ACCEPT_EULA=accept" > /tmp2/silent.cfg                        && \
-    echo "CONTINUE_WITH_OPTIONAL_ERROR=yes" >> /tmp2/silent.cfg         && \
-    echo "PSET_INSTALL_DIR=/opt/intel" >> /tmp2/silent.cfg              && \
-    echo "CONTINUE_WITH_INSTALLDIR_OVERWRITE=yes" >> /tmp2/silent.cfg   && \
-    echo "COMPONENTS=DEFAULTS" >> /tmp2/silent.cfg                      && \
-    echo "COMPONENTS=ALL" >> /tmp2/silent.cfg                           && \
-    echo "PSET_MODE=install" >> /tmp2/silent.cfg                        && \
-    echo "INTEL_SW_IMPROVEMENT_PROGRAM_CONSENT=no" >> /tmp2/silent.cfg  && \
-    echo "SIGNING_ENABLED=no" >> /tmp2/silent.cfg
+RUN echo "ACCEPT_EULA=accept" > /opt/build/openvino/silent.cfg                        && \
+    echo "CONTINUE_WITH_OPTIONAL_ERROR=yes" >> /opt/build/openvino/silent.cfg         && \
+    echo "PSET_INSTALL_DIR=/opt/intel" >> /opt/build/openvino/silent.cfg              && \
+    echo "CONTINUE_WITH_INSTALLDIR_OVERWRITE=yes" >> /opt/build/openvino/silent.cfg   && \
+    echo "COMPONENTS=DEFAULTS" >> /opt/build/openvino/silent.cfg                      && \
+    echo "COMPONENTS=ALL" >> /opt/build/openvino/silent.cfg                           && \
+    echo "PSET_MODE=install" >> /opt/build/openvino/silent.cfg                        && \
+    echo "INTEL_SW_IMPROVEMENT_PROGRAM_CONSENT=no" >> /opt/build/openvino/silent.cfg  && \
+    echo "SIGNING_ENABLED=no" >> /opt/build/openvino/silent.cfg
 
 #Install OpenVino
-RUN /tmp2/${OPENVINO_BUNDLE}/install.sh --ignore-signature --cli-mode -s /tmp2/silent.cfg && rm -rf /tmp2
+RUN /opt/build/openvino/l_openvino_toolkit_p_2020.4.287/install.sh --ignore-signature --cli-mode -s /opt/build/openvino/silent.cfg && rm -rf /opt/build/openvino
 
-#Creat symlink to assure compatibility with components
-RUN cd /opt/intel/      &&\
-    ln -s openvino_2021 openvino
+ARG OPENVINO_IE_DIR=/opt/intel/openvino/deployment_tools/inference_engine
 
+ENV IE_PLUGINS_PATH=${OPENVINO_IE_DIR}/lib/intel64
+ENV HDDL_INSTALL_DIR=${OPENVINO_IE_DIR}/external/hddl
+ENV InferenceEngine_DIR=${OPENVINO_IE_DIR}/share
+ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/openvino/deployment_tools/ngraph/lib:/opt/intel/opencl:$HDDL_INSTALL_DIR/lib:${OPENVINO_IE_DIR}/external/gna/lib:${OPENVINO_IE_DIR}/external/mkltiny_lnx/lib:${OPENVINO_IE_DIR}/external/omp/lib:${OPENVINO_IE_DIR}/external/tbb/lib:/opt/intel/openvino/openvx/lib:$IE_PLUGINS_PATH
 
+#Remove components of OpenVino that are not needed
+ARG CV_BASE_DIR=/opt/intel/openvino
+RUN rm -rf ${CV_BASE_DIR}/uninstall* && \
+    rm -rf ${CV_BASE_DIR}/python && \
+    rm -rf ${CV_BASE_DIR}/documentation && \
+    rm -f ${CV_BASE_DIR}/install_dependencies/*.deb && \
+    rm -rf ${CV_BASE_DIR}/data_processing	&& \
+    rm -rf ${CV_BASE_DIR}/openvino_toolkit_uninstaller && \
+    rm -rf ${CV_BASE_DIR}/deployment_tools/demo && \
+    rm -rf ${CV_BASE_DIR}/deployment_tools/intel_models && \
+    rm -rf ${CV_BASE_DIR}/deployment_tools/model_optimizer && \
+    rm -rf ${CV_BASE_DIR}/deployment_tools/tools && \
+    rm -rf ${CV_BASE_DIR}/deployment_tools/open_model_zoo && \
+    rm -rf ${CV_BASE_DIR}/deployment_tools/inference_engine/samples && \
+    rm -rf ${CV_BASE_DIR}/licensing       && \ 
+    rm -rf ${CV_BASE_DIR}/openvx/samples && \
+    rm -rf ${CV_BASE_DIR}/opencv
 
-RUN cd /opt/intel/openvino/deployment_tools/tools/deployment_manager && \
-    python3 deployment_manager.py --targets=hddl --output_dir=/home --archive_name=hddl && \
-    mkdir -p /home/opt/intel/openvino && \
-    cd /home/opt/intel/openvino && \
-    tar xvf /home/hddl.tar.gz
+#Copy over directories to run image
+RUN mkdir -p /opt/dist/opt/intel && \
+    cp -rH /opt/intel/openvino /opt/dist/opt/intel/
 
-
-#Give all user exec permission
-RUN chmod -R 775 /opt/intel/ ;
-
-
-
-
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc /opt/dist/usr/local/share/gtk-doc
+RUN rm -rf /opt/dist/usr/local/share/man
 
 FROM ubuntu:18.04
+LABEL Description="This is the HDDL Daemon image for ubuntu 18.04"
+LABEL Vendor="Intel Corporation"
+WORKDIR /home
 
-# BUILD TOOLS for HDDLDAEMON run layer image
-RUN apt-get update && apt-get install -y --no-install-recommends sudo libboost-filesystem1.65-dev libboost-thread1.65-dev libboost-program-options1.65-dev libjson-c-dev libusb-1.0-0 autoconf automake make libtool kmod libelf-dev lsb-release wget ca-certificates && \
-    apt-get clean && rm -rf /var/lib/apt/lists/*
-# Build NASM
-ARG NASM_VER=2.13.03
-ARG NASM_REPO=https://www.nasm.us/pub/nasm/releasebuilds/${NASM_VER}/nasm-${NASM_VER}.tar.bz2
-RUN  wget ${NASM_REPO} && \
-     tar -xaf nasm* && \
-     cd nasm-${NASM_VER} && \
-     ./autogen.sh && \
-     ./configure --prefix="/usr/local" --libdir=/usr/local/lib/x86_64-linux-gnu && \
-     make -j8 && \
-     make install
+# Install
+RUN apt-get update && \
+  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+    libboost-filesystem1.65-dev libboost-thread1.65-dev libboost-program-options1.65-dev libjson-c3  && \
+  rm -rf /var/lib/apt/lists/*
+
+COPY --from=build /opt/dist /
+RUN echo "/usr/local/lib" >> /etc/ld.so.conf.d/all-libs.conf && ldconfig
 
 
-COPY --from=builder /lib/x86_64-linux-gnu/libusb-1.0.so.0 /lib/x86_64-linux-gnu/libusb-1.0.so.0
-COPY --from=builder /home/opt/intel /opt/intel
+ARG OPENVINO_IE_DIR=/opt/intel/openvino/deployment_tools/inference_engine
+ENV IE_PLUGINS_PATH=${OPENVINO_IE_DIR}/lib/intel64
+ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/intel/openvino/deployment_tools/ngraph/lib:/opt/intel/opencl:$HDDL_INSTALL_DIR/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/gna/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/mkltiny_lnx/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/omp/lib:/opt/intel/openvino/deployment_tools/inference_engine/external/tbb/lib:/opt/intel/openvino/openvx/lib:/usr/local/lib:$IE_PLUGINS_PATH
+
+#Copy over hddl scripts
 COPY *_hddl.sh /usr/local/bin/
+
diff --git a/Xeon/centos-7/media/ffmpeg/Dockerfile b/Xeon/centos-7/media/ffmpeg/Dockerfile
--- a/Xeon/centos-7/media/ffmpeg/Dockerfile
+++ b/Xeon/centos-7/media/ffmpeg/Dockerfile
@@ -2,9 +2,9 @@
 
 # This file is automatically generated from .m4 template.
 # To update, modify the template and regenerate.
-FROM centos:centos7 AS build
+FROM centos:7 AS build
 
-RUN yum install -y -q epel-release
+RUN yum install -y -q epel-release centos-release-scl && rm -rf /var/yum/cache/*
 
 
 
@@ -12,8 +12,9 @@ RUN mkdir -p /opt/build && mkdir -p /opt/dist
 
 ENV PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig
 
-RUN yum install -y wget make autoconf diffutils automake gcc-c++ epel-release
+RUN yum install -y wget make autoconf diffutils automake gcc-c++
 
+# build libogg
 ARG LIBOGG_REPO=https://downloads.xiph.org/releases/ogg/libogg-1.3.4.tar.gz
 
 RUN cd /opt/build && \
@@ -26,8 +27,8 @@ RUN cd /opt/build && \
 
 RUN yum install -y wget make autoconf diffutils automake
 
+# build libvorbis
 ARG LIBVORBIS_REPO=https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.gz
-
 RUN cd /opt/build && \
     wget -O - ${LIBVORBIS_REPO} | tar xz && \
     cd libvorbis-1.3.7 && \
@@ -38,6 +39,7 @@ RUN cd /opt/build && \
 
 RUN yum install -y wget gcc-c++ autoconf libtool make automake
 
+# build libfdkaac
 ARG LIBFDKAAC_REPO=https://github.com/mstorsjo/fdk-aac/archive/v0.1.6.tar.gz
 RUN cd /opt/build && \
     wget -O - ${LIBFDKAAC_REPO} | tar xz && \
@@ -50,6 +52,7 @@ RUN cd /opt/build && \
 
 RUN yum install -y wget autoconf libtool make
 
+# build libopus
 ARG LIBOPUS_REPO=https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
 RUN cd /opt/build && \
     wget -O - ${LIBOPUS_REPO} | tar xz && \
@@ -61,6 +64,7 @@ RUN cd /opt/build && \
 
 RUN yum install -y wget tar gcc-c++ make bzip2
 
+# build nasm
 ARG NASM_REPO=https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.bz2
 RUN cd /opt/build && \
     wget -O - ${NASM_REPO} | tar xj && \
@@ -72,6 +76,7 @@ RUN cd /opt/build && \
 
 RUN yum install -y git cmake make autoconf diffutils
 
+# build libvpx
 ARG LIBVPX_REPO=https://chromium.googlesource.com/webm/libvpx.git
 RUN cd /opt/build && \
     git clone ${LIBVPX_REPO} -b v1.8.2 --depth 1 && \
@@ -83,17 +88,21 @@ RUN cd /opt/build && \
 
 RUN yum install -y git cmake make autoconf diffutils
 
+# build libx264
 ARG LIBX264_REPO=https://github.com/mirror/x264
 RUN cd /opt/build && \
     git clone ${LIBX264_REPO} -b stable --depth 1 && \
     cd x264 && \
-    ./configure --prefix=/usr/local --libdir=/usr/local/lib64 --enable-shared && \
+    ./configure --prefix=/usr/local --libdir=/usr/local/lib64 \
+        --enable-shared && \
     make -j$(nproc) && \
     make install DESTDIR=/opt/dist && \
     make install
 
 RUN yum install -y wget tar gcc-c++ make
-ARG YASM_REPO=https://github.com/OpenVisualCloud/Dockerfiles-Resources/raw/master/yasm-1.3.0.tar.gz
+
+# build yasm
+ARG YASM_REPO=https://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
 RUN cd /opt/build && \
     wget -O - ${YASM_REPO} | tar xz
 RUN cd /opt/build/yasm-1.3.0 && \
@@ -105,6 +114,7 @@ RUN cd /opt/build/yasm-1.3.0 && \
 
 RUN yum install -y cmake make numactl-devel libpciaccess-devel
 
+# build libx265
 ARG LIBX265_REPO=https://github.com/videolan/x265/archive/3.3.tar.gz
 RUN cd /opt/build && \
     wget -O - ${LIBX265_REPO} | tar xz && \
@@ -115,6 +125,8 @@ RUN cd /opt/build && \
     make install
 
 RUN yum install -y meson wget tar gcc-c++
+
+# build dav1d
 ARG DAV1D_REPO=https://code.videolan.org/videolan/dav1d/-/archive/0.7.1/dav1d-0.7.1.tar.gz
 RUN cd /opt/build && \
   wget -O - ${DAV1D_REPO} | tar xz
@@ -125,83 +137,131 @@ RUN cd /opt/build/dav1d-0.7.1 && \
   DESTDIR=/opt/dist ninja install
 
 RUN yum install -y wget tar gcc-c++ make git cmake3
+
+# build svt-hevc
 ARG SVT_HEVC_REPO=https://github.com/OpenVisualCloud/SVT-HEVC
 RUN cd /opt/build && \
-    git clone ${SVT_HEVC_REPO}
+    git clone -b v1.5.0 --depth 1 ${SVT_HEVC_REPO}
 RUN cd /opt/build/SVT-HEVC/Build/linux && \
-    git checkout v1.5.0 && \
     cmake3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
     make -j $(nproc) && \
     make install DESTDIR=/opt/dist && \
     make install
 
 RUN yum install -y wget tar gcc-c++ make git cmake3
-ARG SVT_AV1_REPO=https://github.com/AOMediaCodec/SVT-AV1
+
+# build svt av1
+ARG SVT_AV1_REPO=https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v0.8.6/SVT-AV1-v0.8.6.tar.gz
 RUN cd /opt/build && \
-    git clone ${SVT_AV1_REPO} -b v0.8.5 --depth 1 && \
+    wget -O - ${SVT_AV1_REPO} | tar zx && \
+    mv SVT-AV1-v0.8.6 SVT-AV1 && \
     cd SVT-AV1/Build/linux && \
     cmake3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
     make -j $(nproc) && \
-    sed -i 's/SvtAv1dec/SvtAv1Dec/' SvtAv1Dec.pc && \
+    sed -i "s/SvtAv1dec/SvtAv1Dec/" SvtAv1Dec.pc && \
     make install DESTDIR=/opt/dist && \
     make install
 
-RUN yum install -y wget tar gcc-c++ make git cmake3 centos-release-scl
+RUN yum install -y wget tar gcc-c++ make git cmake3 devtoolset-9
+
+# build svt vp9
 ARG SVT_VP9_REPO=https://github.com/OpenVisualCloud/SVT-VP9
 RUN cd /opt/build && \
     git clone ${SVT_VP9_REPO} -b v0.2.1 --depth 1 && \
     cd SVT-VP9/Build/linux && \
-  ( yum install -y devtoolset-9-gcc-c++ && \
-    source /opt/rh/devtoolset-9/enable && \
-    cmake3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
-    make -j $(nproc) && \
+    (. /opt/rh/devtoolset-9/enable && cmake3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib64 -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
+    make -j $(nproc) ) && \
     make install DESTDIR=/opt/dist && \
-    make install )
+    make install
 
-RUN yum install -y wget patch libv4l-devel libass-devel freetype-devel 
+RUN yum install -y cmake3 gcc gcc-c++ make wget python36-numpy ccache eigen3-devel
 
+# build opencv
+ARG OPENCV_REPO=https://github.com/opencv/opencv/archive/4.5.1.tar.gz
+RUN cd /opt/build && \
+  wget -O - ${OPENCV_REPO} | tar xz
+# TODO: file a bug against opencv since they do not accept full libdir
+RUN cd /opt/build/opencv-4.5.1 && mkdir build && cd build && \
+  cmake3 \
+    -DCMAKE_BUILD_TYPE=Release \
+    -DCMAKE_INSTALL_PREFIX=/usr/local \
+    -DCMAKE_INSTALL_LIBDIR=lib64 \
+    -DOPENCV_GENERATE_PKGCONFIG=ON \
+    -DBUILD_DOCS=OFF \
+    -DBUILD_EXAMPLES=OFF \
+    -DBUILD_PERF_TESTS=OFF \
+    -DBUILD_TESTS=OFF \
+    .. && \
+  make -j "$(nproc)" && \
+  make install DESTDIR=/opt/dist && \
+  make install
+
+RUN yum install -y wget patch libv4l-devel libass-devel freetype-devel
+
+# build ffmpeg
 ARG FFMPEG_REPO=https://github.com/FFmpeg/FFmpeg/archive/n4.2.2.tar.gz
 RUN cd /opt/build && \
     wget -O - ${FFMPEG_REPO} | tar xz
-
 
 ARG FFMPEG_PATCH_SVT_AV1_REPO=https://github.com/AOMediaCodec/SVT-AV1/archive/v0.8.4.tar.gz
 RUN cd /opt/build && \
     wget -O - ${FFMPEG_PATCH_SVT_AV1_REPO} | tar xz && \
     cd /opt/build/FFmpeg-n4.2.2 && \
     patch -p1 < ../SVT-AV1-0.8.4/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch || true
-
 RUN cd /opt/build/FFmpeg-n4.2.2 && \
     patch -p1 < /opt/build/SVT-HEVC/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch || true
-
 RUN cd /opt/build/FFmpeg-n4.2.2 && \
     patch -p1 < ../SVT-VP9/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch || true
+
+ARG FFMPEG_PATCHES_RELEASE_VER=0.2
+ARG FFMPEG_PATCHES_RELEASE_URL=https://github.com/VCDP/CDN/archive/v${FFMPEG_PATCHES_RELEASE_VER}.tar.gz
+ARG FFMPEG_PATCHES_PATH=/opt/build/CDN-${FFMPEG_PATCHES_RELEASE_VER}
+
+RUN cd /opt/build && \
+    wget -O - ${FFMPEG_PATCHES_RELEASE_URL} | tar xz && \
+    cd /opt/build/FFmpeg-n4.2.2 && \
+    find ${FFMPEG_PATCHES_PATH}/FFmpeg_patches -type f -name *.patch -print0 | sort -z | xargs -t -0 -n 1 patch -p1 -i;
 
 RUN cd /opt/build/FFmpeg-n4.2.2 && \
     ./configure --prefix=/usr/local --libdir=/usr/local/lib64 --enable-shared --disable-static --disable-doc --disable-htmlpages \
     --disable-manpages --disable-podpages --disable-txtpages \
-    --enable-gpl     --enable-nonfree     --enable-libass     --enable-libfreetype     --disable-xlib --disable-sdl2             --disable-vaapi     --enable-libv4l2 --enable-indev=v4l2         --enable-libfdk-aac     --enable-libopus     --enable-libvpx     --enable-libvorbis     --enable-libx264     --enable-libx265     --enable-libsvtav1     --enable-libsvthevc     --enable-libsvtvp9         --enable-libdav1d     && make -j$(nproc) && \
+    --extra-cflags=-w     --enable-gpl     --enable-nonfree     --enable-libass     --enable-libfreetype     --disable-xlib --disable-sdl2     --disable-hwaccels         --disable-vaapi     --enable-libv4l2 --enable-indev=v4l2         --enable-libfdk-aac     --enable-libopus     --enable-libvpx     --enable-libvorbis     --enable-libx264     --enable-libx265     --enable-libsvtav1     --enable-libsvthevc     --enable-libsvtvp9         --enable-libdav1d                     && make -j$(nproc) && \
     make install DESTDIR=/opt/dist && \
     make install
 
-RUN echo "Start cleanup" && \
-    rm -rf /opt/dist//usr/local/include && \
-    rm -rf /opt/dist//usr/local/share/doc && \
-    rm -rf /opt/dist//usr/local/share/gtk-doc && \
-    rm -rf /opt/dist//usr/local/share/man && \
-    ( find /opt/dist -name "*.a" -exec rm -f {} \; ) && \
-    echo "Cleanup done"
+RUN cd /opt/build/opencv-4.5.1/build && \
+  rm -rf ./* && \
+  cmake3 \
+    -DCMAKE_BUILD_TYPE=Release \
+    -DCMAKE_INSTALL_PREFIX=/usr/local \
+    -DCMAKE_INSTALL_LIBDIR=lib64 \
+    -DOPENCV_GENERATE_PKGCONFIG=ON \
+    -DBUILD_DOCS=OFF \
+    -DBUILD_EXAMPLES=OFF \
+    -DBUILD_PERF_TESTS=OFF \
+    -DBUILD_TESTS=OFF \
+    .. && \
+  cd modules/videoio && \
+  make -j "$(nproc)" && \
+  cp -f ../../lib/libopencv_videoio.so.4.5.1 /opt/dist/usr/local/lib64
 
-FROM centos:centos7
-LABEL Description="This is the base image for FFMPEG centos centos7"
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib64/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc /opt/dist/usr/local/share/gtk-doc
+RUN rm -rf /opt/dist/usr/local/share/man
+
+FROM centos:7
+LABEL Description="This is the base image for FFMPEG centos 7"
 LABEL Vendor="Intel Corporation"
 WORKDIR /home
 
-RUN yum install -y -q epel-release
+RUN yum install -y -q epel-release && rm -rf /var/yum/cache/*
 
 
 # Install
-RUN yum install -y numactl-libs libpciaccess libass freetype libv4l 
+RUN yum install -y numactl-libs libpciaccess libv4l libass
 
 COPY --from=build /opt/dist /
 RUN echo "/usr/local/lib64" >> /etc/ld.so.conf.d/all-libs.conf && ldconfig
diff --git a/Xeon/centos-7/media/srs/Dockerfile b/Xeon/centos-7/media/srs/Dockerfile
--- a/Xeon/centos-7/media/srs/Dockerfile
+++ b/Xeon/centos-7/media/srs/Dockerfile
@@ -2,7 +2,7 @@
 
 # This file is automatically generated from .m4 template.
 # To update, modify the template and regenerate.
-FROM centos:centos7 AS build
+FROM centos:7 AS build
 
 
 RUN mkdir -p /opt/build && mkdir -p /opt/dist
@@ -11,20 +11,22 @@ ENV PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig
 
 RUN yum install -y wget tar gcc-c++ make libtool autoconf
 
-ARG OPENSSL_REPO=https://github.com/openssl/openssl/archive/OpenSSL_1_1_1h.tar.gz
+# build openssl
+ARG OPENSSL_REPO=https://github.com/openssl/openssl/archive/OpenSSL_1_1_1i.tar.gz
 RUN cd /opt/build && \
     wget -O - ${OPENSSL_REPO} | tar xz && \
-    cd openssl-OpenSSL_1_1_1h && \
+    cd openssl-OpenSSL_1_1_1i && \
     ./config no-ssl3 shared --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -fPIC -Wl,-rpath=/usr/local/ssl/lib && \
     make depend && \
     make -s V=0 && \
     make install DESTDIR=/opt/dist && \
-    (cd /opt/dist/usr/local && mkdir -p lib64/pkgconfig && mv ssl/lib/pkgconfig/*.pc lib64/pkgconfig) && \
+    (cd /opt/dist && mkdir -p ./usr/local/lib64/pkgconfig && mv ./usr/local/ssl/lib/pkgconfig/*.pc ./usr/local/lib64/pkgconfig/) && \
     make install && \
-    (cd /usr/local && mkdir -p lib64/pkgconfig && mv ssl/lib/pkgconfig/*.pc lib64/pkgconfig)
+    (mkdir -p /usr/local/lib64/pkgconfig && mv /usr/local/ssl/lib/pkgconfig/*.pc /usr/local/lib64/pkgconfig/)
 
 RUN yum install -y git gcc-c++ make unzip patch pkg-config 
 
+# build srs
 ARG SRS_REPO=https://github.com/ossrs/srs.git
 RUN cd /opt/build && \
     git clone -b v4.0.62 --depth 1 ${SRS_REPO} && \
@@ -50,16 +52,18 @@ RUN cd /opt/build && \
 RUN echo /opt/dist
 RUN ls /opt/dist
 
-RUN echo "Start cleanup" && \
-    rm -rf /opt/dist//usr/local/include && \
-    rm -rf /opt/dist//usr/local/share/doc && \
-    rm -rf /opt/dist//usr/local/share/gtk-doc && \
-    rm -rf /opt/dist//usr/local/share/man && \
-    ( find /opt/dist -name "*.a" -exec rm -f {} \; ) && \
-    echo "Cleanup done"
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib64/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc /opt/dist/usr/local/share/gtk-doc
+RUN rm -rf /opt/dist/usr/local/share/man
+RUN rm -rf /opt/dist/usr/local/ssl/include
+RUN rm -rf /opt/dist/usr/local/ssl/share/man
+RUN rm -rf /opt/dist/usr/local/ssl/share/doc
 
 FROM openvisualcloud/xeon-centos7-media-ffmpeg:latest
-LABEL Description="This is the base image for Media SRS centos centos7"
+LABEL Description="This is the base image for Media SRS centos 7"
 LABEL Vendor="Intel Corporation"
 WORKDIR /home
 
diff --git a/Xeon/ubuntu-18.04/media/ffmpeg/Dockerfile b/Xeon/ubuntu-18.04/media/ffmpeg/Dockerfile
--- a/Xeon/ubuntu-18.04/media/ffmpeg/Dockerfile
+++ b/Xeon/ubuntu-18.04/media/ffmpeg/Dockerfile
@@ -14,6 +14,7 @@ RUN apt-get update && \
     ca-certificates wget make autoconf automake g++ && \
   rm -rf /var/lib/apt/lists/*
 
+# build libogg
 ARG LIBOGG_REPO=https://downloads.xiph.org/releases/ogg/libogg-1.3.4.tar.gz
 
 RUN cd /opt/build && \
@@ -29,8 +30,8 @@ RUN apt-get update && \
     ca-certificates wget make autoconf automake && \
   rm -rf /var/lib/apt/lists/*
 
+# build libvorbis
 ARG LIBVORBIS_REPO=https://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.gz
-
 RUN cd /opt/build && \
     wget -O - ${LIBVORBIS_REPO} | tar xz && \
     cd libvorbis-1.3.7 && \
@@ -44,6 +45,7 @@ RUN apt-get update && \
     ca-certificates wget g++ autoconf libtool autotools-dev automake make && \
   rm -rf /var/lib/apt/lists/*
 
+# build libfdkaac
 ARG LIBFDKAAC_REPO=https://github.com/mstorsjo/fdk-aac/archive/v0.1.6.tar.gz
 RUN cd /opt/build && \
     wget -O - ${LIBFDKAAC_REPO} | tar xz && \
@@ -59,6 +61,7 @@ RUN apt-get update && \
     ca-certificates wget autoconf libtool make && \
   rm -rf /var/lib/apt/lists/*
 
+# build libopus
 ARG LIBOPUS_REPO=https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
 RUN cd /opt/build && \
     wget -O - ${LIBOPUS_REPO} | tar xz && \
@@ -73,6 +76,7 @@ RUN apt-get update && \
     ca-certificates wget tar g++ make bzip2 && \
   rm -rf /var/lib/apt/lists/*
 
+# build nasm
 ARG NASM_REPO=https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.bz2
 RUN cd /opt/build && \
     wget -O - ${NASM_REPO} | tar xj && \
@@ -87,6 +91,7 @@ RUN apt-get update && \
     git cmake make autoconf && \
   rm -rf /var/lib/apt/lists/*
 
+# build libvpx
 ARG LIBVPX_REPO=https://chromium.googlesource.com/webm/libvpx.git
 RUN cd /opt/build && \
     git clone ${LIBVPX_REPO} -b v1.8.2 --depth 1 && \
@@ -101,11 +106,13 @@ RUN apt-get update && \
     git cmake make autoconf && \
   rm -rf /var/lib/apt/lists/*
 
+# build libx264
 ARG LIBX264_REPO=https://github.com/mirror/x264
 RUN cd /opt/build && \
     git clone ${LIBX264_REPO} -b stable --depth 1 && \
     cd x264 && \
-    ./configure --prefix=/usr/local --libdir=/usr/local/lib --enable-shared && \
+    ./configure --prefix=/usr/local --libdir=/usr/local/lib \
+        --enable-shared && \
     make -j$(nproc) && \
     make install DESTDIR=/opt/dist && \
     make install
@@ -114,7 +121,9 @@ RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
     ca-certificates wget tar g++ make && \
   rm -rf /var/lib/apt/lists/*
-ARG YASM_REPO=https://github.com/OpenVisualCloud/Dockerfiles-Resources/raw/master/yasm-1.3.0.tar.gz
+
+# build yasm
+ARG YASM_REPO=https://www.tortall.net/projects/yasm/releases/yasm-1.3.0.tar.gz
 RUN cd /opt/build && \
     wget -O - ${YASM_REPO} | tar xz
 RUN cd /opt/build/yasm-1.3.0 && \
@@ -129,6 +138,7 @@ RUN apt-get update && \
     libnuma-dev cmake make && \
   rm -rf /var/lib/apt/lists/*
 
+# build libx265
 ARG LIBX265_REPO=https://github.com/videolan/x265/archive/3.3.tar.gz
 RUN cd /opt/build && \
     wget -O - ${LIBX265_REPO} | tar xz && \
@@ -140,8 +150,10 @@ RUN cd /opt/build && \
 
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    python3-setuptools && \
+    python3-pip ninja-build python3-setuptools && \
   rm -rf /var/lib/apt/lists/*
+
+# build meson
 ARG MESON_REPO=https://github.com/mesonbuild/meson
 RUN git clone ${MESON_REPO}; \
     cd meson; \
@@ -150,8 +162,10 @@ RUN git clone ${MESON_REPO}; \
 
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    ca-certificates meson tar g++ wget pkg-config && \
+    ca-certificates tar g++ wget pkg-config && \
   rm -rf /var/lib/apt/lists/*
+
+# build dav1d
 ARG DAV1D_REPO=https://code.videolan.org/videolan/dav1d/-/archive/0.7.1/dav1d-0.7.1.tar.gz
 RUN cd /opt/build && \
   wget -O - ${DAV1D_REPO} | tar xz
@@ -165,11 +179,12 @@ RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
     ca-certificates wget tar g++ make cmake git && \
   rm -rf /var/lib/apt/lists/*
+
+# build svt-hevc
 ARG SVT_HEVC_REPO=https://github.com/OpenVisualCloud/SVT-HEVC
 RUN cd /opt/build && \
-    git clone ${SVT_HEVC_REPO}
+    git clone -b v1.5.0 --depth 1 ${SVT_HEVC_REPO}
 RUN cd /opt/build/SVT-HEVC/Build/linux && \
-    git checkout v1.5.0 && \
     cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
     make -j $(nproc) && \
     make install DESTDIR=/opt/dist && \
@@ -179,13 +194,16 @@ RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
     ca-certificates wget tar g++ make cmake git && \
   rm -rf /var/lib/apt/lists/*
-ARG SVT_AV1_REPO=https://github.com/AOMediaCodec/SVT-AV1
+
+# build svt av1
+ARG SVT_AV1_REPO=https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v0.8.6/SVT-AV1-v0.8.6.tar.gz
 RUN cd /opt/build && \
-    git clone ${SVT_AV1_REPO} -b v0.8.5 --depth 1 && \
+    wget -O - ${SVT_AV1_REPO} | tar zx && \
+    mv SVT-AV1-v0.8.6 SVT-AV1 && \
     cd SVT-AV1/Build/linux && \
     cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
     make -j $(nproc) && \
-    sed -i 's/SvtAv1dec/SvtAv1Dec/' SvtAv1Dec.pc && \
+    sed -i "s/SvtAv1dec/SvtAv1Dec/" SvtAv1Dec.pc && \
     make install DESTDIR=/opt/dist && \
     make install
 
@@ -193,6 +211,8 @@ RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
     ca-certificates wget tar g++ make cmake git && \
   rm -rf /var/lib/apt/lists/*
+
+# build svt vp9
 ARG SVT_VP9_REPO=https://github.com/OpenVisualCloud/SVT-VP9
 RUN cd /opt/build && \
     git clone ${SVT_VP9_REPO} -b v0.2.1 --depth 1 && \
@@ -200,44 +220,91 @@ RUN cd /opt/build && \
     cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
     make -j $(nproc) && \
     make install DESTDIR=/opt/dist && \
-    make install 
+    make install
 
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    ca-certificates wget patch libv4l-dev libass-dev  && \
+    ca-certificates cmake gcc g++ make wget python3-numpy ccache libeigen3-dev && \
   rm -rf /var/lib/apt/lists/*
 
+# build opencv
+ARG OPENCV_REPO=https://github.com/opencv/opencv/archive/4.5.1.tar.gz
+RUN cd /opt/build && \
+  wget -O - ${OPENCV_REPO} | tar xz
+# TODO: file a bug against opencv since they do not accept full libdir
+RUN cd /opt/build/opencv-4.5.1 && mkdir build && cd build && \
+  cmake \
+    -DCMAKE_BUILD_TYPE=Release \
+    -DCMAKE_INSTALL_PREFIX=/usr/local \
+    -DCMAKE_INSTALL_LIBDIR=lib \
+    -DOPENCV_GENERATE_PKGCONFIG=ON \
+    -DBUILD_DOCS=OFF \
+    -DBUILD_EXAMPLES=OFF \
+    -DBUILD_PERF_TESTS=OFF \
+    -DBUILD_TESTS=OFF \
+    .. && \
+  make -j "$(nproc)" && \
+  make install DESTDIR=/opt/dist && \
+  make install
+
+RUN apt-get update && \
+  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
+    build-essential ca-certificates wget patch libv4l-dev libass-dev  && \
+  rm -rf /var/lib/apt/lists/*
+
+# build ffmpeg
 ARG FFMPEG_REPO=https://github.com/FFmpeg/FFmpeg/archive/n4.2.2.tar.gz
 RUN cd /opt/build && \
     wget -O - ${FFMPEG_REPO} | tar xz
-
 
 ARG FFMPEG_PATCH_SVT_AV1_REPO=https://github.com/AOMediaCodec/SVT-AV1/archive/v0.8.4.tar.gz
 RUN cd /opt/build && \
     wget -O - ${FFMPEG_PATCH_SVT_AV1_REPO} | tar xz && \
     cd /opt/build/FFmpeg-n4.2.2 && \
     patch -p1 < ../SVT-AV1-0.8.4/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch || true
-
 RUN cd /opt/build/FFmpeg-n4.2.2 && \
     patch -p1 < /opt/build/SVT-HEVC/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch || true
-
 RUN cd /opt/build/FFmpeg-n4.2.2 && \
     patch -p1 < ../SVT-VP9/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-vp9.patch || true
+
+ARG FFMPEG_PATCHES_RELEASE_VER=0.2
+ARG FFMPEG_PATCHES_RELEASE_URL=https://github.com/VCDP/CDN/archive/v${FFMPEG_PATCHES_RELEASE_VER}.tar.gz
+ARG FFMPEG_PATCHES_PATH=/opt/build/CDN-${FFMPEG_PATCHES_RELEASE_VER}
+
+RUN cd /opt/build && \
+    wget -O - ${FFMPEG_PATCHES_RELEASE_URL} | tar xz && \
+    cd /opt/build/FFmpeg-n4.2.2 && \
+    find ${FFMPEG_PATCHES_PATH}/FFmpeg_patches -type f -name *.patch -print0 | sort -z | xargs -t -0 -n 1 patch -p1 -i;
 
 RUN cd /opt/build/FFmpeg-n4.2.2 && \
     ./configure --prefix=/usr/local --libdir=/usr/local/lib --enable-shared --disable-static --disable-doc --disable-htmlpages \
     --disable-manpages --disable-podpages --disable-txtpages \
-    --enable-gpl     --enable-nonfree     --enable-libass     --enable-libfreetype     --disable-xlib --disable-sdl2             --disable-vaapi     --enable-libv4l2 --enable-indev=v4l2         --enable-libfdk-aac     --enable-libopus     --enable-libvpx     --enable-libvorbis     --enable-libx264     --enable-libx265     --enable-libsvtav1     --enable-libsvthevc     --enable-libsvtvp9         --enable-libdav1d     && make -j$(nproc) && \
+    --extra-cflags=-w     --enable-gpl     --enable-nonfree     --enable-libass     --enable-libfreetype     --disable-xlib --disable-sdl2     --disable-hwaccels         --disable-vaapi     --enable-libv4l2 --enable-indev=v4l2         --enable-libfdk-aac     --enable-libopus     --enable-libvpx     --enable-libvorbis     --enable-libx264     --enable-libx265     --enable-libsvtav1     --enable-libsvthevc     --enable-libsvtvp9         --enable-libdav1d                     && make -j$(nproc) && \
     make install DESTDIR=/opt/dist && \
     make install
 
-RUN echo "Start cleanup" && \
-    rm -rf /opt/dist//usr/local/include && \
-    rm -rf /opt/dist//usr/local/share/doc && \
-    rm -rf /opt/dist//usr/local/share/gtk-doc && \
-    rm -rf /opt/dist//usr/local/share/man && \
-    ( find /opt/dist -name "*.a" -exec rm -f {} \; ) && \
-    echo "Cleanup done"
+RUN cd /opt/build/opencv-4.5.1/build && \
+  rm -rf ./* && \
+  cmake \
+    -DCMAKE_BUILD_TYPE=Release \
+    -DCMAKE_INSTALL_PREFIX=/usr/local \
+    -DCMAKE_INSTALL_LIBDIR=lib \
+    -DOPENCV_GENERATE_PKGCONFIG=ON \
+    -DBUILD_DOCS=OFF \
+    -DBUILD_EXAMPLES=OFF \
+    -DBUILD_PERF_TESTS=OFF \
+    -DBUILD_TESTS=OFF \
+    .. && \
+  cd modules/videoio && \
+  make -j "$(nproc)" && \
+  cp -f ../../lib/libopencv_videoio.so.4.5.1 /opt/dist/usr/local/lib
+
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc /opt/dist/usr/local/share/gtk-doc
+RUN rm -rf /opt/dist/usr/local/share/man
 
 FROM ubuntu:18.04
 LABEL Description="This is the base image for FFMPEG ubuntu 18.04"
@@ -247,7 +314,7 @@ WORKDIR /home
 # Install
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    libnuma1 libass9 libv4l-0  && \
+    libnuma1 libxcb-shape0 libxcb-xfixes0 libv4l-0 libass9  && \
   rm -rf /var/lib/apt/lists/*
 
 COPY --from=build /opt/dist /
diff --git a/Xeon/ubuntu-20.04/media/srs/Dockerfile b/Xeon/ubuntu-20.04/media/srs/Dockerfile
--- a/Xeon/ubuntu-20.04/media/srs/Dockerfile
+++ b/Xeon/ubuntu-20.04/media/srs/Dockerfile
@@ -14,23 +14,25 @@ RUN apt-get update && \
     ca-certificates wget tar g++ make libtool autoconf && \
   rm -rf /var/lib/apt/lists/*
 
-ARG OPENSSL_REPO=https://github.com/openssl/openssl/archive/OpenSSL_1_1_1h.tar.gz
+# build openssl
+ARG OPENSSL_REPO=https://github.com/openssl/openssl/archive/OpenSSL_1_1_1i.tar.gz
 RUN cd /opt/build && \
     wget -O - ${OPENSSL_REPO} | tar xz && \
-    cd openssl-OpenSSL_1_1_1h && \
+    cd openssl-OpenSSL_1_1_1i && \
     ./config no-ssl3 shared --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -fPIC -Wl,-rpath=/usr/local/ssl/lib && \
     make depend && \
     make -s V=0 && \
     make install DESTDIR=/opt/dist && \
-    (cd /opt/dist/usr/local && mkdir -p lib/pkgconfig && mv ssl/lib/pkgconfig/*.pc lib/pkgconfig) && \
+    (cd /opt/dist && mkdir -p ./usr/local/lib/pkgconfig && mv ./usr/local/ssl/lib/pkgconfig/*.pc ./usr/local/lib/pkgconfig/) && \
     make install && \
-    (cd /usr/local && mkdir -p lib/pkgconfig && mv ssl/lib/pkgconfig/*.pc lib/pkgconfig)
+    (mkdir -p /usr/local/lib/pkgconfig && mv /usr/local/ssl/lib/pkgconfig/*.pc /usr/local/lib/pkgconfig/)
 
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
     git ca-certificates g++ make unzip patch pkg-config  && \
   rm -rf /var/lib/apt/lists/*
 
+# build srs
 ARG SRS_REPO=https://github.com/ossrs/srs.git
 RUN cd /opt/build && \
     git clone -b v4.0.62 --depth 1 ${SRS_REPO} && \
@@ -56,13 +58,15 @@ RUN cd /opt/build && \
 RUN echo /opt/dist
 RUN ls /opt/dist
 
-RUN echo "Start cleanup" && \
-    rm -rf /opt/dist//usr/local/include && \
-    rm -rf /opt/dist//usr/local/share/doc && \
-    rm -rf /opt/dist//usr/local/share/gtk-doc && \
-    rm -rf /opt/dist//usr/local/share/man && \
-    ( find /opt/dist -name "*.a" -exec rm -f {} \; ) && \
-    echo "Cleanup done"
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc /opt/dist/usr/local/share/gtk-doc
+RUN rm -rf /opt/dist/usr/local/share/man
+RUN rm -rf /opt/dist/usr/local/ssl/include
+RUN rm -rf /opt/dist/usr/local/ssl/share/man
+RUN rm -rf /opt/dist/usr/local/ssl/share/doc
 
 FROM openvisualcloud/xeon-ubuntu2004-media-ffmpeg:latest
 LABEL Description="This is the base image for Media SRS ubuntu 20.04"
