support u1804

diff --git a/Xeon/ubuntu-18.04/analytics/dev/Dockerfile b/Xeon/ubuntu-18.04/analytics/dev/Dockerfile
--- a/Xeon/ubuntu-18.04/analytics/dev/Dockerfile
+++ b/Xeon/ubuntu-18.04/analytics/dev/Dockerfile
@@ -118,7 +118,8 @@ ARG LIBX264_REPO=https://github.com/mirror/x264
 RUN cd /opt/build && \
     git clone ${LIBX264_REPO} -b stable --depth 1 && \
     cd x264 && \
-    ./configure --prefix=/usr/local --libdir=/usr/local/lib --enable-shared && \
+    ./configure --prefix=/usr/local --libdir=/usr/local/lib \
+        --enable-shared && \
     make -j$(nproc) && \
     make install DESTDIR=/opt/dist && \
     make install
@@ -153,7 +154,7 @@ RUN cd /opt/build && \
 
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    python3-setuptools && \
+    python3-pip ninja-build python3-setuptools && \
   rm -rf /var/lib/apt/lists/*
 ARG MESON_REPO=https://github.com/mesonbuild/meson
 RUN git clone ${MESON_REPO}; \
@@ -163,7 +164,7 @@ RUN git clone ${MESON_REPO}; \
 
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    ca-certificates meson tar g++ wget pkg-config && \
+    ca-certificates tar g++ wget pkg-config && \
   rm -rf /var/lib/apt/lists/*
 ARG DAV1D_REPO=https://code.videolan.org/videolan/dav1d/-/archive/0.7.1/dav1d-0.7.1.tar.gz
 RUN cd /opt/build && \
@@ -180,9 +181,8 @@ RUN apt-get update && \
   rm -rf /var/lib/apt/lists/*
 ARG SVT_HEVC_REPO=https://github.com/OpenVisualCloud/SVT-HEVC
 RUN cd /opt/build && \
-    git clone ${SVT_HEVC_REPO}
+    git clone -b v1.5.0 --depth 1 ${SVT_HEVC_REPO}
 RUN cd /opt/build/SVT-HEVC/Build/linux && \
-    git checkout v1.5.0 && \
     cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_INSTALL_LIBDIR=/usr/local/lib -DCMAKE_ASM_NASM_COMPILER=yasm ../.. && \
     make -j $(nproc) && \
     make install DESTDIR=/opt/dist && \
@@ -217,7 +217,7 @@ RUN cd /opt/build && \
 
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    ca-certificates meson tar g++ wget pkg-config libglib2.0-dev flex bison  && \
+    ca-certificates tar g++ wget pkg-config libglib2.0-dev flex bison  && \
   rm -rf /var/lib/apt/lists/*
 ARG GSTCORE_REPO=https://github.com/GStreamer/gstreamer/archive/1.16.2.tar.gz
 RUN cd /opt/build && \
@@ -225,6 +225,9 @@ RUN cd /opt/build && \
 RUN cd /opt/build/gstreamer-1.16.2 && \
     meson build --libdir=/usr/local/lib --libexecdir=/usr/local/lib \
     --prefix=/usr/local --buildtype=plain \
+    -Dbenchmarks=disabled \
+    -Dexamples=disabled \
+    -Dtests=disabled \
     -Dgtk_doc=disabled && \
     cd build && \
     ninja install && \
@@ -236,14 +239,19 @@ RUN apt-get update && \
   rm -rf /var/lib/apt/lists/*
 ARG GSTBASE_REPO=https://github.com/GStreamer/gst-plugins-base/archive/1.16.2.tar.gz
 RUN cd /opt/build && \
-    wget -O - ${GSTBASE_REPO} | tar xz
+  wget -O - ${GSTBASE_REPO} | tar xz
 RUN cd /opt/build/gst-plugins-base-1.16.2 && \
-    meson build --libdir=/usr/local/lib --libexecdir=/usr/local/lib \
-    --prefix=/usr/local --buildtype=plain \
+  meson build \
+    --prefix=/usr/local \
+    --libdir=/usr/local/lib \
+    --libexecdir=/usr/local/lib \
+    --buildtype=plain \
+    -Dexamples=disabled \
+    -Dtests=disabled \
     -Dgtk_doc=disabled && \
-    cd build && \
-    ninja install && \
-    DESTDIR=/opt/dist ninja install
+  cd build && \
+  ninja install && \
+  DESTDIR=/opt/dist ninja install
 
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
@@ -262,18 +270,24 @@ RUN cd /opt/build/gst-plugins-good-1.16.2 && \
 
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
-    ca-certificates meson tar g++ wget pkg-config libglib2.0-dev flex bison openssl libcurl4-gnutls-dev librtmp-dev mjpegtools libde265-dev && \
+    ca-certificates tar g++ wget pkg-config libglib2.0-dev flex bison openssl libcurl4-gnutls-dev librtmp-dev mjpegtools libde265-dev && \
   rm -rf /var/lib/apt/lists/*
 ARG GSTBAD_REPO=https://github.com/GStreamer/gst-plugins-bad/archive/1.16.2.tar.gz
 RUN cd /opt/build && \
     wget -O - ${GSTBAD_REPO} | tar xz
 RUN cd /opt/build/gst-plugins-bad-1.16.2 && \
-    meson build --libdir=/usr/local/lib --libexecdir=/usr/local/lib \
-    --prefix=/usr/local --buildtype=plain \
-    -Dgtk_doc=disabled && \
-    cd build && \
-    ninja install && \
-    DESTDIR=/opt/dist ninja install
+  meson build \
+    --prefix=/usr/local \
+    --libdir=/usr/local/lib \
+    --libexecdir=/usr/local/lib \
+    --buildtype=plain \
+    -Ddoc=disabled \
+    -Dexamples=disabled \
+    -Dgtk_doc=disabled \
+    -Dtests=disabled && \
+  cd build && \
+  ninja install && \
+  DESTDIR=/opt/dist ninja install
 
 RUN apt-get update && \
   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
@@ -363,27 +377,40 @@ RUN apt-get update && \
   rm -rf /var/lib/apt/lists/*
 ARG DLDT_REPO=https://github.com/openvinotoolkit/openvino.git
 
-RUN cd /opt/build && git clone -b 2021.1 ${DLDT_REPO} && \
-  cd openvino && \
-  git submodule update --init --recursive && \
+RUN git clone ${DLDT_REPO} /opt/build/openvino && \
+  cd /opt/build/openvino && \
+  git checkout 2021.2 && \
+  git submodule update --init --recursive
+
+# TODO:
+# Perform make install of openvino instead of manually copying build artifacts.
+#
+# For now, only ngraph target is installed using make install (it auto-generates .cmake
+# files during install stage, so they can be later used by other projects).
+
+RUN cd /opt/build/openvino && \
   sed -i s/-Werror//g $(grep -ril Werror inference-engine/thirdparty/) && \
-  mkdir build && \
-  cd build && \
+  mkdir build && cd build && \
   cmake \
-    -DCMAKE_INSTALL_PREFIX=PREFIX_BUILD/dldt \
+    -DCMAKE_INSTALL_PREFIX=/usr/local/dldt \
+    -DENABLE_CPPLINT=OFF \
     -DENABLE_GNA=OFF \
     -DENABLE_VPU=OFF \
     -DENABLE_OPENCV=OFF \
-    -DTREAT_WARNING_AS_ERROR=OFF \
-    -DNGRAPH_WARNINGS_AS_ERRORS=OFF \
     -DENABLE_MKL_DNN=ON \
     -DENABLE_CLDNN=ON \
+    -DENABLE_SAMPLES=OFF \
     -DENABLE_TESTS=OFF \
     -DBUILD_TESTS=OFF \
+    -DTREAT_WARNING_AS_ERROR=OFF \
+    -DNGRAPH_WARNINGS_AS_ERRORS=OFF \
+    -DNGRAPH_COMPONENT_PREFIX=inference-engine/ \
     -DNGRAPH_UNIT_TEST_ENABLE=OFF \
     -DNGRAPH_TEST_UTIL_ENABLE=OFF \
     .. && \
   make -j $(nproc) && \
+  make -C ngraph install && \
+  make -C ngraph install DESTDIR=/opt/dist && \
   rm -rf ../bin/intel64/Release/lib/libgtest* && \
   rm -rf ../bin/intel64/Release/lib/libgmock* && \
   rm -rf ../bin/intel64/Release/lib/libmock* && \
@@ -392,6 +419,10 @@ RUN cd /opt/build && git clone -b 2021.1 ${DLDT_REPO} && \
 ARG CUSTOM_IE_DIR=/usr/local/dldt/inference-engine
 ARG CUSTOM_IE_LIBDIR=${CUSTOM_IE_DIR}/lib/intel64
 ENV CUSTOM_DLDT=${CUSTOM_IE_DIR}
+
+ENV InferenceEngine_DIR=/usr/local/dldt/inference-engine/share
+ENV TBB_DIR=/usr/local/dldt/inference-engine/external/tbb/cmake
+ENV ngraph_DIR=/usr/local/dldt/inference-engine/cmake
 
 RUN cd /opt/build && \
   mkdir -p ${CUSTOM_IE_DIR}/include && \
@@ -415,8 +446,8 @@ RUN cd /opt/build && \
   mkdir -p /opt/dist/${CUSTOM_IE_DIR}/external && \
   cp -r openvino/build/share/* ${CUSTOM_IE_DIR}/share/ && \
   cp -r openvino/build/share/* /opt/dist/${CUSTOM_IE_DIR}/share/ && \
-  cp -r openvino/inference-engine/temp/* ${CUSTOM_IE_DIR}/external/ && \
-  cp -r openvino/inference-engine/temp/* /opt/dist/${CUSTOM_IE_DIR}/external/ && \
+  cp -r openvino/inference-engine/temp/tbb ${CUSTOM_IE_DIR}/external/ && \
+  cp -r openvino/inference-engine/temp/tbb /opt/dist/${CUSTOM_IE_DIR}/external/ && \
   \
   mkdir -p "${CUSTOM_IE_LIBDIR}/pkgconfig"
 
@@ -433,15 +464,14 @@ RUN { \
   echo "Cflags: -I\${includedir}"; \
   } > ${CUSTOM_IE_LIBDIR}/pkgconfig/dldt.pc
 
-RUN rm -rf openvino
+RUN rm -rf /opt/build/openvino
 
-RUN echo "Start cleanup" && \
-    rm -rf /opt/dist//usr/local/include && \
-    rm -rf /opt/dist//usr/local/share/doc && \
-    rm -rf /opt/dist//usr/local/share/gtk-doc && \
-    rm -rf /opt/dist//usr/local/share/man && \
-    ( find /opt/dist -name "*.a" -exec rm -f {} \; ) && \
-    echo "Cleanup done"
+# cleanup
+RUN rm -rf /opt/dist/usr/local/include && \
+    rm -rf /opt/dist/usr/local/lib/pkgconfig && \
+    find /opt/dist -name "*.a" -exec rm -f {} \; || echo ""
+RUN rm -rf /opt/dist/usr/local/share/doc /opt/dist/usr/local/share/gtk-doc
+RUN rm -rf /opt/dist/usr/local/share/man
 
 FROM ubuntu:18.04
 LABEL Description="This is the base image for Development purposes on ubuntu 18.04"
@@ -464,7 +494,6 @@ ARG CUSTOM_IE_LIBDIR=${CUSTOM_IE_DIR}/lib/intel64
 RUN { \
    echo "${CUSTOM_IE_LIBDIR}"; \
    echo "${CUSTOM_IE_DIR}/external/tbb/lib"; \
-   echo "${CUSTOM_IE_DIR}/external/opencv/lib"; \
 } > /etc/ld.so.conf.d/dldt.conf
 RUN ldconfig
 
